language: php

matrix:
    fast_finish: true
    include:
      - php: 7.4
      - php: 8.0
      - php: nightly
    allow_failures:
      - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script:
    - vendor/bin/grumphp run
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
